# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'cfanmain.ui'
#
# Created by: PyQt5 UI code generator 5.14.1
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(897, 583)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(24)
        sizePolicy.setVerticalStretch(24)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        MainWindow.setMinimumSize(QtCore.QSize(24, 24))
        font = QtGui.QFont()
        font.setFamily("Ubuntu")
        font.setPointSize(10)
        MainWindow.setFont(font)
        MainWindow.setStyleSheet("")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.groupBox_control = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_control.setGeometry(QtCore.QRect(20, 210, 421, 321))
        self.groupBox_control.setFlat(False)
        self.groupBox_control.setCheckable(False)
        self.groupBox_control.setObjectName("groupBox_control")
        self.gridLayoutWidget = QtWidgets.QWidget(self.groupBox_control)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(20, 37, 381, 271))
        self.gridLayoutWidget.setObjectName("gridLayoutWidget")
        self.gridLayout_control = QtWidgets.QGridLayout(self.gridLayoutWidget)
        self.gridLayout_control.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_control.setObjectName("gridLayout_control")
        self.speed_fan6 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.speed_fan6.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.speed_fan6.setObjectName("speed_fan6")
        self.gridLayout_control.addWidget(self.speed_fan6, 6, 3, 1, 1)
        self.header_PWM = QtWidgets.QLabel(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("Ubuntu")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.header_PWM.setFont(font)
        self.header_PWM.setAlignment(QtCore.Qt.AlignCenter)
        self.header_PWM.setObjectName("header_PWM")
        self.gridLayout_control.addWidget(self.header_PWM, 0, 4, 1, 1)
        self.pushButton_fan6 = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.pushButton_fan6.setMinimumSize(QtCore.QSize(0, 36))
        self.pushButton_fan6.setCheckable(True)
        self.pushButton_fan6.setAutoExclusive(True)
        self.pushButton_fan6.setFlat(True)
        self.pushButton_fan6.setObjectName("pushButton_fan6")
        self.gridLayout_control.addWidget(self.pushButton_fan6, 6, 1, 1, 1)
        self.pushButton_fan1 = QtWidgets.QPushButton(self.gridLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_fan1.sizePolicy().hasHeightForWidth())
        self.pushButton_fan1.setSizePolicy(sizePolicy)
        self.pushButton_fan1.setMinimumSize(QtCore.QSize(100, 36))
        font = QtGui.QFont()
        font.setFamily("Ubuntu")
        font.setPointSize(10)
        self.pushButton_fan1.setFont(font)
        self.pushButton_fan1.setCheckable(True)
        self.pushButton_fan1.setAutoExclusive(True)
        self.pushButton_fan1.setFlat(True)
        self.pushButton_fan1.setObjectName("pushButton_fan1")
        self.gridLayout_control.addWidget(self.pushButton_fan1, 1, 1, 1, 1)
        self.mode_fan2 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.mode_fan2.setAlignment(QtCore.Qt.AlignCenter)
        self.mode_fan2.setObjectName("mode_fan2")
        self.gridLayout_control.addWidget(self.mode_fan2, 2, 2, 1, 1)
        self.icon_fan1 = QtWidgets.QLabel(self.gridLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.icon_fan1.sizePolicy().hasHeightForWidth())
        self.icon_fan1.setSizePolicy(sizePolicy)
        self.icon_fan1.setMinimumSize(QtCore.QSize(0, 0))
        self.icon_fan1.setText("")
        self.icon_fan1.setPixmap(QtGui.QPixmap(":/fans/fan_connected.png"))
        self.icon_fan1.setObjectName("icon_fan1")
        self.gridLayout_control.addWidget(self.icon_fan1, 1, 0, 1, 1)
        self.speed_fan5 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.speed_fan5.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.speed_fan5.setObjectName("speed_fan5")
        self.gridLayout_control.addWidget(self.speed_fan5, 5, 3, 1, 1)
        self.speed_fan4 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.speed_fan4.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.speed_fan4.setObjectName("speed_fan4")
        self.gridLayout_control.addWidget(self.speed_fan4, 4, 3, 1, 1)
        self.pushButton_fan5 = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.pushButton_fan5.setMinimumSize(QtCore.QSize(0, 36))
        self.pushButton_fan5.setCheckable(True)
        self.pushButton_fan5.setAutoExclusive(True)
        self.pushButton_fan5.setFlat(True)
        self.pushButton_fan5.setObjectName("pushButton_fan5")
        self.gridLayout_control.addWidget(self.pushButton_fan5, 5, 1, 1, 1)
        self.icon_fan2 = QtWidgets.QLabel(self.gridLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.icon_fan2.sizePolicy().hasHeightForWidth())
        self.icon_fan2.setSizePolicy(sizePolicy)
        self.icon_fan2.setText("")
        self.icon_fan2.setPixmap(QtGui.QPixmap(":/fans/fan_disconnected.png"))
        self.icon_fan2.setScaledContents(False)
        self.icon_fan2.setObjectName("icon_fan2")
        self.gridLayout_control.addWidget(self.icon_fan2, 2, 0, 1, 1)
        self.mode_fan4 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.mode_fan4.setAlignment(QtCore.Qt.AlignCenter)
        self.mode_fan4.setObjectName("mode_fan4")
        self.gridLayout_control.addWidget(self.mode_fan4, 4, 2, 1, 1)
        self.header_channel = QtWidgets.QLabel(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("Ubuntu")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.header_channel.setFont(font)
        self.header_channel.setAlignment(QtCore.Qt.AlignCenter)
        self.header_channel.setObjectName("header_channel")
        self.gridLayout_control.addWidget(self.header_channel, 0, 1, 1, 1)
        self.mode_fan3 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.mode_fan3.setAlignment(QtCore.Qt.AlignCenter)
        self.mode_fan3.setObjectName("mode_fan3")
        self.gridLayout_control.addWidget(self.mode_fan3, 3, 2, 1, 1)
        self.speed_fan2 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.speed_fan2.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.speed_fan2.setObjectName("speed_fan2")
        self.gridLayout_control.addWidget(self.speed_fan2, 2, 3, 1, 1)
        self.mode_fan1 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.mode_fan1.setAlignment(QtCore.Qt.AlignCenter)
        self.mode_fan1.setObjectName("mode_fan1")
        self.gridLayout_control.addWidget(self.mode_fan1, 1, 2, 1, 1)
        self.pushButton_fan3 = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.pushButton_fan3.setMinimumSize(QtCore.QSize(0, 36))
        self.pushButton_fan3.setCheckable(True)
        self.pushButton_fan3.setAutoExclusive(True)
        self.pushButton_fan3.setFlat(True)
        self.pushButton_fan3.setObjectName("pushButton_fan3")
        self.gridLayout_control.addWidget(self.pushButton_fan3, 3, 1, 1, 1)
        self.speed_fan3 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.speed_fan3.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.speed_fan3.setObjectName("speed_fan3")
        self.gridLayout_control.addWidget(self.speed_fan3, 3, 3, 1, 1)
        self.icon_fan3 = QtWidgets.QLabel(self.gridLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.icon_fan3.sizePolicy().hasHeightForWidth())
        self.icon_fan3.setSizePolicy(sizePolicy)
        self.icon_fan3.setMinimumSize(QtCore.QSize(0, 0))
        self.icon_fan3.setText("")
        self.icon_fan3.setPixmap(QtGui.QPixmap(":/fans/fan_connected.png"))
        self.icon_fan3.setObjectName("icon_fan3")
        self.gridLayout_control.addWidget(self.icon_fan3, 3, 0, 1, 1)
        self.icon_fan5 = QtWidgets.QLabel(self.gridLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.icon_fan5.sizePolicy().hasHeightForWidth())
        self.icon_fan5.setSizePolicy(sizePolicy)
        self.icon_fan5.setText("")
        self.icon_fan5.setPixmap(QtGui.QPixmap(":/fans/fan_disconnected.png"))
        self.icon_fan5.setScaledContents(False)
        self.icon_fan5.setObjectName("icon_fan5")
        self.gridLayout_control.addWidget(self.icon_fan5, 5, 0, 1, 1)
        self.pushButton_fan4 = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.pushButton_fan4.setMinimumSize(QtCore.QSize(0, 36))
        self.pushButton_fan4.setCheckable(True)
        self.pushButton_fan4.setAutoExclusive(True)
        self.pushButton_fan4.setFlat(True)
        self.pushButton_fan4.setObjectName("pushButton_fan4")
        self.gridLayout_control.addWidget(self.pushButton_fan4, 4, 1, 1, 1)
        self.mode_fan5 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.mode_fan5.setAlignment(QtCore.Qt.AlignCenter)
        self.mode_fan5.setObjectName("mode_fan5")
        self.gridLayout_control.addWidget(self.mode_fan5, 5, 2, 1, 1)
        self.header_speed = QtWidgets.QLabel(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("Ubuntu")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.header_speed.setFont(font)
        self.header_speed.setAlignment(QtCore.Qt.AlignCenter)
        self.header_speed.setObjectName("header_speed")
        self.gridLayout_control.addWidget(self.header_speed, 0, 3, 1, 1)
        self.icon_fan6 = QtWidgets.QLabel(self.gridLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.icon_fan6.sizePolicy().hasHeightForWidth())
        self.icon_fan6.setSizePolicy(sizePolicy)
        self.icon_fan6.setText("")
        self.icon_fan6.setPixmap(QtGui.QPixmap(":/fans/fan_disconnected.png"))
        self.icon_fan6.setScaledContents(False)
        self.icon_fan6.setObjectName("icon_fan6")
        self.gridLayout_control.addWidget(self.icon_fan6, 6, 0, 1, 1)
        self.icon_fan4 = QtWidgets.QLabel(self.gridLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.icon_fan4.sizePolicy().hasHeightForWidth())
        self.icon_fan4.setSizePolicy(sizePolicy)
        self.icon_fan4.setText("")
        self.icon_fan4.setPixmap(QtGui.QPixmap(":/fans/fan_disconnected.png"))
        self.icon_fan4.setScaledContents(False)
        self.icon_fan4.setObjectName("icon_fan4")
        self.gridLayout_control.addWidget(self.icon_fan4, 4, 0, 1, 1)
        self.speed_fan1 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.speed_fan1.setStyleSheet("")
        self.speed_fan1.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.speed_fan1.setObjectName("speed_fan1")
        self.gridLayout_control.addWidget(self.speed_fan1, 1, 3, 1, 1)
        self.pushButton_fan2 = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.pushButton_fan2.setMinimumSize(QtCore.QSize(0, 36))
        self.pushButton_fan2.setCheckable(True)
        self.pushButton_fan2.setChecked(False)
        self.pushButton_fan2.setAutoExclusive(True)
        self.pushButton_fan2.setFlat(True)
        self.pushButton_fan2.setObjectName("pushButton_fan2")
        self.gridLayout_control.addWidget(self.pushButton_fan2, 2, 1, 1, 1)
        self.header_mode = QtWidgets.QLabel(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("Ubuntu")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.header_mode.setFont(font)
        self.header_mode.setAlignment(QtCore.Qt.AlignCenter)
        self.header_mode.setObjectName("header_mode")
        self.gridLayout_control.addWidget(self.header_mode, 0, 2, 1, 1)
        self.mode_fan6 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.mode_fan6.setAlignment(QtCore.Qt.AlignCenter)
        self.mode_fan6.setObjectName("mode_fan6")
        self.gridLayout_control.addWidget(self.mode_fan6, 6, 2, 1, 1)
        self.header_temp = QtWidgets.QLabel(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("Ubuntu")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.header_temp.setFont(font)
        self.header_temp.setAlignment(QtCore.Qt.AlignCenter)
        self.header_temp.setObjectName("header_temp")
        self.gridLayout_control.addWidget(self.header_temp, 0, 5, 1, 1)
        self.pwm_fan1 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.pwm_fan1.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.pwm_fan1.setObjectName("pwm_fan1")
        self.gridLayout_control.addWidget(self.pwm_fan1, 1, 4, 1, 1)
        self.pwm_fan2 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.pwm_fan2.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.pwm_fan2.setObjectName("pwm_fan2")
        self.gridLayout_control.addWidget(self.pwm_fan2, 2, 4, 1, 1)
        self.pwm_fan3 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.pwm_fan3.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.pwm_fan3.setObjectName("pwm_fan3")
        self.gridLayout_control.addWidget(self.pwm_fan3, 3, 4, 1, 1)
        self.pwm_fan4 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.pwm_fan4.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.pwm_fan4.setObjectName("pwm_fan4")
        self.gridLayout_control.addWidget(self.pwm_fan4, 4, 4, 1, 1)
        self.pwm_fan5 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.pwm_fan5.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.pwm_fan5.setObjectName("pwm_fan5")
        self.gridLayout_control.addWidget(self.pwm_fan5, 5, 4, 1, 1)
        self.pwm_fan6 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.pwm_fan6.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.pwm_fan6.setObjectName("pwm_fan6")
        self.gridLayout_control.addWidget(self.pwm_fan6, 6, 4, 1, 1)
        self.temp_fan1 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.temp_fan1.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.temp_fan1.setObjectName("temp_fan1")
        self.gridLayout_control.addWidget(self.temp_fan1, 1, 5, 1, 1)
        self.temp_fan2 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.temp_fan2.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.temp_fan2.setObjectName("temp_fan2")
        self.gridLayout_control.addWidget(self.temp_fan2, 2, 5, 1, 1)
        self.temp_fan3 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.temp_fan3.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.temp_fan3.setObjectName("temp_fan3")
        self.gridLayout_control.addWidget(self.temp_fan3, 3, 5, 1, 1)
        self.temp_fan4 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.temp_fan4.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.temp_fan4.setObjectName("temp_fan4")
        self.gridLayout_control.addWidget(self.temp_fan4, 4, 5, 1, 1)
        self.temp_fan5 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.temp_fan5.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.temp_fan5.setObjectName("temp_fan5")
        self.gridLayout_control.addWidget(self.temp_fan5, 5, 5, 1, 1)
        self.temp_fan6 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.temp_fan6.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.temp_fan6.setObjectName("temp_fan6")
        self.gridLayout_control.addWidget(self.temp_fan6, 6, 5, 1, 1)
        self.groupBox_mode = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_mode.setEnabled(False)
        self.groupBox_mode.setGeometry(QtCore.QRect(460, 20, 421, 511))
        self.groupBox_mode.setObjectName("groupBox_mode")
        self.gridLayoutWidget_2 = QtWidgets.QWidget(self.groupBox_mode)
        self.gridLayoutWidget_2.setGeometry(QtCore.QRect(20, 30, 301, 112))
        self.gridLayoutWidget_2.setObjectName("gridLayoutWidget_2")
        self.gridLayout_mode = QtWidgets.QGridLayout(self.gridLayoutWidget_2)
        self.gridLayout_mode.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_mode.setObjectName("gridLayout_mode")
        self.radioButton_curve = QtWidgets.QRadioButton(self.gridLayoutWidget_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.radioButton_curve.sizePolicy().hasHeightForWidth())
        self.radioButton_curve.setSizePolicy(sizePolicy)
        self.radioButton_curve.setMinimumSize(QtCore.QSize(130, 0))
        self.radioButton_curve.setAutoExclusive(True)
        self.radioButton_curve.setObjectName("radioButton_curve")
        self.gridLayout_mode.addWidget(self.radioButton_curve, 2, 0, 1, 1)
        self.radioButton_fixed = QtWidgets.QRadioButton(self.gridLayoutWidget_2)
        self.radioButton_fixed.setAutoExclusive(True)
        self.radioButton_fixed.setObjectName("radioButton_fixed")
        self.gridLayout_mode.addWidget(self.radioButton_fixed, 1, 0, 1, 1)
        self.radioButton_off = QtWidgets.QRadioButton(self.gridLayoutWidget_2)
        self.radioButton_off.setAutoExclusive(True)
        self.radioButton_off.setObjectName("radioButton_off")
        self.gridLayout_mode.addWidget(self.radioButton_off, 0, 0, 1, 1)
        self.spinBox_fixed = QtWidgets.QSpinBox(self.gridLayoutWidget_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.spinBox_fixed.sizePolicy().hasHeightForWidth())
        self.spinBox_fixed.setSizePolicy(sizePolicy)
        self.spinBox_fixed.setMinimumSize(QtCore.QSize(99, 30))
        self.spinBox_fixed.setMaximum(100)
        self.spinBox_fixed.setSingleStep(5)
        self.spinBox_fixed.setObjectName("spinBox_fixed")
        self.gridLayout_mode.addWidget(self.spinBox_fixed, 1, 1, 1, 1)
        self.comboBox_sensors = QtWidgets.QComboBox(self.gridLayoutWidget_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.comboBox_sensors.sizePolicy().hasHeightForWidth())
        self.comboBox_sensors.setSizePolicy(sizePolicy)
        self.comboBox_sensors.setMinimumSize(QtCore.QSize(140, 0))
        self.comboBox_sensors.setFrame(False)
        self.comboBox_sensors.setObjectName("comboBox_sensors")
        self.comboBox_sensors.addItem("")
        self.comboBox_sensors.addItem("")
        self.gridLayout_mode.addWidget(self.comboBox_sensors, 2, 1, 1, 1)
        self.pushButton_apply = QtWidgets.QPushButton(self.groupBox_mode)
        self.pushButton_apply.setGeometry(QtCore.QRect(340, 107, 61, 31))
        self.pushButton_apply.setFlat(False)
        self.pushButton_apply.setObjectName("pushButton_apply")
        self.frame_fancurve = QtWidgets.QFrame(self.groupBox_mode)
        self.frame_fancurve.setGeometry(QtCore.QRect(20, 145, 380, 355))
        self.frame_fancurve.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_fancurve.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_fancurve.setObjectName("frame_fancurve")
        self.graphicsView_fancurve = PlotWidget(self.frame_fancurve)
        self.graphicsView_fancurve.setGeometry(QtCore.QRect(10, 45, 360, 300))
        self.graphicsView_fancurve.setObjectName("graphicsView_fancurve")
        self.pushButton_remove = QtWidgets.QPushButton(self.frame_fancurve)
        self.pushButton_remove.setEnabled(False)
        self.pushButton_remove.setGeometry(QtCore.QRect(350, 12, 20, 20))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_remove.sizePolicy().hasHeightForWidth())
        self.pushButton_remove.setSizePolicy(sizePolicy)
        self.pushButton_remove.setMaximumSize(QtCore.QSize(38, 16777215))
        self.pushButton_remove.setObjectName("pushButton_remove")
        self.pushButton_add = QtWidgets.QPushButton(self.frame_fancurve)
        self.pushButton_add.setEnabled(False)
        self.pushButton_add.setGeometry(QtCore.QRect(325, 12, 20, 20))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_add.sizePolicy().hasHeightForWidth())
        self.pushButton_add.setSizePolicy(sizePolicy)
        self.pushButton_add.setMaximumSize(QtCore.QSize(38, 16777215))
        self.pushButton_add.setObjectName("pushButton_add")
        self.pushButton_linear_curve = QtWidgets.QPushButton(self.frame_fancurve)
        self.pushButton_linear_curve.setEnabled(False)
        self.pushButton_linear_curve.setGeometry(QtCore.QRect(60, 10, 24, 24))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_linear_curve.sizePolicy().hasHeightForWidth())
        self.pushButton_linear_curve.setSizePolicy(sizePolicy)
        self.pushButton_linear_curve.setMaximumSize(QtCore.QSize(38, 16777215))
        self.pushButton_linear_curve.setStyleSheet("")
        self.pushButton_linear_curve.setText("")
        self.pushButton_linear_curve.setFlat(False)
        self.pushButton_linear_curve.setObjectName("pushButton_linear_curve")
        self.pushButton_exponential_curve = QtWidgets.QPushButton(self.frame_fancurve)
        self.pushButton_exponential_curve.setEnabled(False)
        self.pushButton_exponential_curve.setGeometry(QtCore.QRect(90, 10, 24, 24))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_exponential_curve.sizePolicy().hasHeightForWidth())
        self.pushButton_exponential_curve.setSizePolicy(sizePolicy)
        self.pushButton_exponential_curve.setMaximumSize(QtCore.QSize(38, 16777215))
        self.pushButton_exponential_curve.setText("")
        self.pushButton_exponential_curve.setFlat(False)
        self.pushButton_exponential_curve.setObjectName("pushButton_exponential_curve")
        self.pushButton_logistic_curve = QtWidgets.QPushButton(self.frame_fancurve)
        self.pushButton_logistic_curve.setEnabled(False)
        self.pushButton_logistic_curve.setGeometry(QtCore.QRect(120, 10, 24, 24))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_logistic_curve.sizePolicy().hasHeightForWidth())
        self.pushButton_logistic_curve.setSizePolicy(sizePolicy)
        self.pushButton_logistic_curve.setMaximumSize(QtCore.QSize(38, 16777215))
        self.pushButton_logistic_curve.setText("")
        self.pushButton_logistic_curve.setFlat(False)
        self.pushButton_logistic_curve.setObjectName("pushButton_logistic_curve")
        self.pushButton_semi_exp_curve = QtWidgets.QPushButton(self.frame_fancurve)
        self.pushButton_semi_exp_curve.setEnabled(False)
        self.pushButton_semi_exp_curve.setGeometry(QtCore.QRect(150, 10, 24, 24))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_semi_exp_curve.sizePolicy().hasHeightForWidth())
        self.pushButton_semi_exp_curve.setSizePolicy(sizePolicy)
        self.pushButton_semi_exp_curve.setMaximumSize(QtCore.QSize(38, 16777215))
        self.pushButton_semi_exp_curve.setText("")
        self.pushButton_semi_exp_curve.setFlat(False)
        self.pushButton_semi_exp_curve.setObjectName("pushButton_semi_exp_curve")
        self.pushButton_semi_logistic_curve = QtWidgets.QPushButton(self.frame_fancurve)
        self.pushButton_semi_logistic_curve.setEnabled(False)
        self.pushButton_semi_logistic_curve.setGeometry(QtCore.QRect(180, 10, 24, 24))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_semi_logistic_curve.sizePolicy().hasHeightForWidth())
        self.pushButton_semi_logistic_curve.setSizePolicy(sizePolicy)
        self.pushButton_semi_logistic_curve.setMaximumSize(QtCore.QSize(38, 16777215))
        self.pushButton_semi_logistic_curve.setText("")
        self.pushButton_semi_logistic_curve.setFlat(False)
        self.pushButton_semi_logistic_curve.setObjectName("pushButton_semi_logistic_curve")
        self.label_presets = QtWidgets.QLabel(self.frame_fancurve)
        self.label_presets.setGeometry(QtCore.QRect(10, 12, 50, 20))
        font = QtGui.QFont()
        font.setFamily("Ubuntu")
        font.setPointSize(9)
        self.label_presets.setFont(font)
        self.label_presets.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_presets.setObjectName("label_presets")
        self.label_segments = QtWidgets.QLabel(self.frame_fancurve)
        self.label_segments.setGeometry(QtCore.QRect(245, 12, 71, 20))
        font = QtGui.QFont()
        font.setFamily("Ubuntu")
        font.setPointSize(9)
        self.label_segments.setFont(font)
        self.label_segments.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_segments.setObjectName("label_segments")
        self.groupBox_daemon = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_daemon.setGeometry(QtCore.QRect(20, 20, 421, 151))
        self.groupBox_daemon.setObjectName("groupBox_daemon")
        self.label_daemon = QtWidgets.QLabel(self.groupBox_daemon)
        self.label_daemon.setGeometry(QtCore.QRect(10, 35, 111, 16))
        self.label_daemon.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_daemon.setObjectName("label_daemon")
        self.label_Interval = QtWidgets.QLabel(self.groupBox_daemon)
        self.label_Interval.setGeometry(QtCore.QRect(10, 75, 111, 16))
        self.label_Interval.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_Interval.setObjectName("label_Interval")
        self.label_profiles = QtWidgets.QLabel(self.groupBox_daemon)
        self.label_profiles.setGeometry(QtCore.QRect(10, 115, 111, 16))
        self.label_profiles.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_profiles.setObjectName("label_profiles")
        self.comboBox_profiles = QtWidgets.QComboBox(self.groupBox_daemon)
        self.comboBox_profiles.setGeometry(QtCore.QRect(140, 110, 161, 24))
        self.comboBox_profiles.setFrame(True)
        self.comboBox_profiles.setObjectName("comboBox_profiles")
        self.pushButton_add_profile = QtWidgets.QPushButton(self.groupBox_daemon)
        self.pushButton_add_profile.setEnabled(True)
        self.pushButton_add_profile.setGeometry(QtCore.QRect(310, 110, 24, 24))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_add_profile.sizePolicy().hasHeightForWidth())
        self.pushButton_add_profile.setSizePolicy(sizePolicy)
        self.pushButton_add_profile.setMaximumSize(QtCore.QSize(38, 16777215))
        self.pushButton_add_profile.setFlat(False)
        self.pushButton_add_profile.setObjectName("pushButton_add_profile")
        self.pushButton_remove_profile = QtWidgets.QPushButton(self.groupBox_daemon)
        self.pushButton_remove_profile.setEnabled(True)
        self.pushButton_remove_profile.setGeometry(QtCore.QRect(340, 110, 24, 24))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_remove_profile.sizePolicy().hasHeightForWidth())
        self.pushButton_remove_profile.setSizePolicy(sizePolicy)
        self.pushButton_remove_profile.setMaximumSize(QtCore.QSize(38, 16777215))
        self.pushButton_remove_profile.setFlat(False)
        self.pushButton_remove_profile.setObjectName("pushButton_remove_profile")
        self.switch_daemon = Switch(self.groupBox_daemon)
        self.switch_daemon.setGeometry(QtCore.QRect(140, 33, 40, 20))
        self.switch_daemon.setToolTip("")
        self.switch_daemon.setWhatsThis("")
        self.switch_daemon.setProperty("checked", False)
        self.switch_daemon.setProperty("track_radius", 10)
        self.switch_daemon.setProperty("thumb_radius", 8)
        self.switch_daemon.setObjectName("switch_daemon")
        self.slider_interval = QtWidgets.QSlider(self.groupBox_daemon)
        self.slider_interval.setGeometry(QtCore.QRect(140, 75, 101, 20))
        self.slider_interval.setMinimum(1)
        self.slider_interval.setMaximum(30)
        self.slider_interval.setPageStep(5)
        self.slider_interval.setProperty("value", 1)
        self.slider_interval.setSliderPosition(1)
        self.slider_interval.setOrientation(QtCore.Qt.Horizontal)
        self.slider_interval.setObjectName("slider_interval")
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.menuBar = QtWidgets.QMenuBar(MainWindow)
        self.menuBar.setGeometry(QtCore.QRect(0, 0, 897, 28))
        self.menuBar.setObjectName("menuBar")
        self.menuFile = QtWidgets.QMenu(self.menuBar)
        self.menuFile.setObjectName("menuFile")
        self.menuOptions = QtWidgets.QMenu(self.menuBar)
        self.menuOptions.setObjectName("menuOptions")
        self.menuTheme = QtWidgets.QMenu(self.menuOptions)
        self.menuTheme.setObjectName("menuTheme")
        self.menu_Log_Level = QtWidgets.QMenu(self.menuOptions)
        self.menu_Log_Level.setObjectName("menu_Log_Level")
        MainWindow.setMenuBar(self.menuBar)
        self.actionLoad_Profile = QtWidgets.QAction(MainWindow)
        self.actionLoad_Profile.setObjectName("actionLoad_Profile")
        self.actionSave_Profile = QtWidgets.QAction(MainWindow)
        self.actionSave_Profile.setObjectName("actionSave_Profile")
        self.actionQuit = QtWidgets.QAction(MainWindow)
        self.actionQuit.setObjectName("actionQuit")
        self.actionSave_Settings = QtWidgets.QAction(MainWindow)
        self.actionSave_Settings.setObjectName("actionSave_Settings")
        self.actionLight = QtWidgets.QAction(MainWindow)
        self.actionLight.setCheckable(True)
        self.actionLight.setChecked(True)
        self.actionLight.setObjectName("actionLight")
        self.actionDark = QtWidgets.QAction(MainWindow)
        self.actionDark.setCheckable(True)
        self.actionDark.setObjectName("actionDark")
        self.actionSystem = QtWidgets.QAction(MainWindow)
        self.actionSystem.setCheckable(True)
        self.actionSystem.setObjectName("actionSystem")
        self.action_Off = QtWidgets.QAction(MainWindow)
        self.action_Off.setCheckable(True)
        self.action_Off.setObjectName("action_Off")
        self.action_Debug = QtWidgets.QAction(MainWindow)
        self.action_Debug.setCheckable(True)
        self.action_Debug.setObjectName("action_Debug")
        self.action_Info = QtWidgets.QAction(MainWindow)
        self.action_Info.setCheckable(True)
        self.action_Info.setObjectName("action_Info")
        self.action_Warning = QtWidgets.QAction(MainWindow)
        self.action_Warning.setCheckable(True)
        self.action_Warning.setObjectName("action_Warning")
        self.action_Error = QtWidgets.QAction(MainWindow)
        self.action_Error.setCheckable(True)
        self.action_Error.setObjectName("action_Error")
        self.actionAbout = QtWidgets.QAction(MainWindow)
        self.actionAbout.setObjectName("actionAbout")
        self.menuFile.addAction(self.actionLoad_Profile)
        self.menuFile.addAction(self.actionSave_Profile)
        self.menuFile.addSeparator()
        self.menuFile.addAction(self.actionSave_Settings)
        self.menuFile.addSeparator()
        self.menuFile.addAction(self.actionQuit)
        self.menuTheme.addAction(self.actionLight)
        self.menuTheme.addAction(self.actionDark)
        self.menuTheme.addAction(self.actionSystem)
        self.menu_Log_Level.addAction(self.action_Off)
        self.menu_Log_Level.addAction(self.action_Debug)
        self.menu_Log_Level.addAction(self.action_Info)
        self.menu_Log_Level.addAction(self.action_Warning)
        self.menu_Log_Level.addAction(self.action_Error)
        self.menuOptions.addAction(self.menuTheme.menuAction())
        self.menuOptions.addAction(self.menu_Log_Level.menuAction())
        self.menuOptions.addSeparator()
        self.menuOptions.addAction(self.actionAbout)
        self.menuBar.addAction(self.menuFile.menuAction())
        self.menuBar.addAction(self.menuOptions.menuAction())

        self.retranslateUi(MainWindow)
        self.comboBox_sensors.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)
        MainWindow.setTabOrder(self.comboBox_profiles, self.pushButton_add_profile)
        MainWindow.setTabOrder(self.pushButton_add_profile, self.pushButton_remove_profile)
        MainWindow.setTabOrder(self.pushButton_remove_profile, self.pushButton_fan1)
        MainWindow.setTabOrder(self.pushButton_fan1, self.pushButton_fan2)
        MainWindow.setTabOrder(self.pushButton_fan2, self.pushButton_fan3)
        MainWindow.setTabOrder(self.pushButton_fan3, self.pushButton_fan4)
        MainWindow.setTabOrder(self.pushButton_fan4, self.pushButton_fan5)
        MainWindow.setTabOrder(self.pushButton_fan5, self.pushButton_fan6)
        MainWindow.setTabOrder(self.pushButton_fan6, self.radioButton_off)
        MainWindow.setTabOrder(self.radioButton_off, self.radioButton_fixed)
        MainWindow.setTabOrder(self.radioButton_fixed, self.spinBox_fixed)
        MainWindow.setTabOrder(self.spinBox_fixed, self.radioButton_curve)
        MainWindow.setTabOrder(self.radioButton_curve, self.pushButton_apply)
        MainWindow.setTabOrder(self.pushButton_apply, self.graphicsView_fancurve)
        MainWindow.setTabOrder(self.graphicsView_fancurve, self.pushButton_add)
        MainWindow.setTabOrder(self.pushButton_add, self.pushButton_remove)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Commander Pro Commander"))
        self.groupBox_control.setTitle(_translate("MainWindow", "Fan Control"))
        self.speed_fan6.setText(_translate("MainWindow", "0 rpm"))
        self.header_PWM.setText(_translate("MainWindow", "PWM"))
        self.pushButton_fan6.setText(_translate("MainWindow", "Fan 6"))
        self.pushButton_fan1.setText(_translate("MainWindow", "Fan 1"))
        self.mode_fan2.setText(_translate("MainWindow", "Off"))
        self.speed_fan5.setText(_translate("MainWindow", "0 rpm"))
        self.speed_fan4.setText(_translate("MainWindow", "0 rpm"))
        self.pushButton_fan5.setText(_translate("MainWindow", "Fan 5"))
        self.mode_fan4.setText(_translate("MainWindow", "Off"))
        self.header_channel.setText(_translate("MainWindow", "Channel"))
        self.mode_fan3.setText(_translate("MainWindow", "Off"))
        self.speed_fan2.setText(_translate("MainWindow", "0 rpm"))
        self.mode_fan1.setText(_translate("MainWindow", "Dynamic"))
        self.pushButton_fan3.setText(_translate("MainWindow", "Fan 3"))
        self.speed_fan3.setText(_translate("MainWindow", "0 rpm"))
        self.pushButton_fan4.setText(_translate("MainWindow", "Fan 4"))
        self.mode_fan5.setText(_translate("MainWindow", "Off"))
        self.header_speed.setText(_translate("MainWindow", "Speed"))
        self.speed_fan1.setText(_translate("MainWindow", "0 rpm"))
        self.pushButton_fan2.setText(_translate("MainWindow", "Fan 2"))
        self.header_mode.setText(_translate("MainWindow", "Mode"))
        self.mode_fan6.setText(_translate("MainWindow", "Off"))
        self.header_temp.setText(_translate("MainWindow", "Temp"))
        self.pwm_fan1.setText(_translate("MainWindow", "0 %"))
        self.pwm_fan2.setText(_translate("MainWindow", "0 %"))
        self.pwm_fan3.setText(_translate("MainWindow", "0 %"))
        self.pwm_fan4.setText(_translate("MainWindow", "0 %"))
        self.pwm_fan5.setText(_translate("MainWindow", "0 %"))
        self.pwm_fan6.setText(_translate("MainWindow", "0 %"))
        self.temp_fan1.setText(_translate("MainWindow", "0.0° C"))
        self.temp_fan2.setText(_translate("MainWindow", "0.0° C"))
        self.temp_fan3.setText(_translate("MainWindow", "0.0° C"))
        self.temp_fan4.setText(_translate("MainWindow", "0.0° C"))
        self.temp_fan5.setText(_translate("MainWindow", "0.0° C"))
        self.temp_fan6.setText(_translate("MainWindow", "0.0° C"))
        self.groupBox_mode.setTitle(_translate("MainWindow", "Fan Mode"))
        self.radioButton_curve.setText(_translate("MainWindow", "Dynamic, based on"))
        self.radioButton_fixed.setText(_translate("MainWindow", "Fixed"))
        self.radioButton_off.setText(_translate("MainWindow", "Off"))
        self.spinBox_fixed.setSuffix(_translate("MainWindow", " %"))
        self.comboBox_sensors.setCurrentText(_translate("MainWindow", "<none>"))
        self.comboBox_sensors.setItemText(0, _translate("MainWindow", "<none>"))
        self.comboBox_sensors.setItemText(1, _translate("MainWindow", "CPU"))
        self.pushButton_apply.setText(_translate("MainWindow", "Apply"))
        self.pushButton_remove.setText(_translate("MainWindow", "-"))
        self.pushButton_add.setText(_translate("MainWindow", "+"))
        self.label_presets.setText(_translate("MainWindow", "Presets"))
        self.label_segments.setText(_translate("MainWindow", "Segments"))
        self.groupBox_daemon.setTitle(_translate("MainWindow", "Fan Manager"))
        self.label_daemon.setText(_translate("MainWindow", "Update Daemon"))
        self.label_Interval.setText(_translate("MainWindow", "Update Interval"))
        self.label_profiles.setText(_translate("MainWindow", "Active Profile"))
        self.pushButton_add_profile.setText(_translate("MainWindow", "+"))
        self.pushButton_remove_profile.setText(_translate("MainWindow", "-"))
        self.menuFile.setTitle(_translate("MainWindow", "&File"))
        self.menuOptions.setTitle(_translate("MainWindow", "&Options"))
        self.menuTheme.setTitle(_translate("MainWindow", "&Theme"))
        self.menu_Log_Level.setTitle(_translate("MainWindow", "&Log Level"))
        self.actionLoad_Profile.setText(_translate("MainWindow", "&Load Profile..."))
        self.actionSave_Profile.setText(_translate("MainWindow", "Save &Profile..."))
        self.actionQuit.setText(_translate("MainWindow", "E&xit"))
        self.actionSave_Settings.setText(_translate("MainWindow", "&Save Settings"))
        self.actionLight.setText(_translate("MainWindow", "&Light"))
        self.actionDark.setText(_translate("MainWindow", "&Dark"))
        self.actionSystem.setText(_translate("MainWindow", "&System"))
        self.action_Off.setText(_translate("MainWindow", "&Off"))
        self.action_Debug.setText(_translate("MainWindow", "&Debug"))
        self.action_Info.setText(_translate("MainWindow", "&Info"))
        self.action_Warning.setText(_translate("MainWindow", "&Warning"))
        self.action_Error.setText(_translate("MainWindow", "&Error"))
        self.actionAbout.setText(_translate("MainWindow", "&About"))
from .switch import Switch
from pyqtgraph import PlotWidget
from . import resources_rc
